FROM eclipse-temurin:21-jre
WORKDIR /app
COPY target/yaob-backend-3.1.0.jar app.jar
ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENV SPRING_PROFILES_ACTIVE=prod
EXPOSE 8100
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
